-- AlterTable
ALTER TABLE "Barang" ALTER COLUMN "hargaBeli" SET DATA TYPE BIGINT,
ALTER COLUMN "hargaJual" SET DATA TYPE BIGINT,
ALTER COLUMN "ukuran" SET DATA TYPE BIGINT,
ALTER COLUMN "jumlahPerkardus" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "PembelianItem" ALTER COLUMN "jumlahDus" SET DATA TYPE BIGINT;
